### ISSUE TITLE
init-near-contracts fail at call init on eth-client contract

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#109]
It's reproducible to me everytime, but seems okay to @nearmax ,  Maybe a nodejs version specific issue. My reproduce:
```
node index.js clean
node index.js prepare
node index.js start near-node
node index.js start ganache
./scripts/start_ganache.sh # in a separate window
node index.js init-near-contracts

Key to call Eth2NearClient contract is not specified. Reusing master key.
Key to call Eth2NearProver contract is not specified. Reusing master key.
Creating accounts and deploying the contracts.
Account eth2nearclient does not exist creating it.
Created account eth2nearclient
Deployed contract to account eth2nearclient
Account eth2nearprover does not exist creating it.
Created account eth2nearprover
Deployed contract to account eth2nearprover
Initializing client and prover contracts.
EthClient is not initialized, initializing...
TxHash 7J8LwQSRQmtUWUJBGpeFpLjYW1RvAu6EXMxjQKqHot67
Failed:  InvalidTxError: {}
    at Object.parseRpcError (/Users/bo/workspace/rainbow-bridge/environment/node_modules/nearlib/lib/utils/rpc_errors.js:25:19)
    at JsonRpcProvider.sendJsonRpc (/Users/bo/workspace/rainbow-bridge/environment/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async signAndSendTransaction (/Users/bo/workspace/rainbow-bridge/environment/lib/borsh/index.js:203:20)
    at async Eth2NearClientContract.value [as init] (/Users/bo/workspace/rainbow-bridge/environment/lib/borsh/index.js:246:43)
    at async Eth2NearClientContract.maybeInitialize (/Users/bo/workspace/rainbow-bridge/environment/lib/eth2near-client-contract/index.js:114:13)
    at async Command.execute (/Users/bo/workspace/rainbow-bridge/environment/commands/init-near-contracts.js:64:9)
    at async Promise.all (index 0)
    at async /Users/bo/workspace/rainbow-bridge/environment/index.js:365:16 {
  type: 'InvalidTxError'
}
(node:33437) UnhandledPromiseRejectionWarning: Error: {}
    at Object.parseRpcError (/Users/bo/workspace/rainbow-bridge/environment/node_modules/nearlib/lib/utils/rpc_errors.js:25:19)
    at JsonRpcProvider.sendJsonRpc (/Users/bo/workspace/rainbow-bridge/environment/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async signAndSendTransaction (/Users/bo/workspace/rainbow-bridge/environment/lib/borsh/index.js:203:20)
    at async Eth2NearClientContract.value [as init] (/Users/bo/workspace/rainbow-bridge/environment/lib/borsh/index.js:246:43)
    at async Eth2NearClientContract.maybeInitialize (/Users/bo/workspace/rainbow-bridge/environment/lib/eth2near-client-contract/index.js:114:13)
    at async Command.execute (/Users/bo/workspace/rainbow-bridge/environment/commands/init-near-contracts.js:64:9)
    at async Promise.all (index 0)
    at async /Users/bo/workspace/rainbow-bridge/environment/index.js:365:16
(node:33437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nearmax** [comment]
Are you using the most recent nearcore node?

**Comment by nearmax** [comment]
Is it failing on CI only or also on your laptop?

**Comment by ailisp** [comment]
Yes, ~/.rainbowup/core `git log` looks so. It's failing on my laptop

**Comment by nearmax** [comment]
@ailisp Do you run each command manually or with some script? Also, where can I find the configuration of the CI

**Comment by nearmax** [comment]
I can reproduce it now.

**Comment by ailisp** [comment]
> @ailisp Do you run each command manually or with some script? Also, where can I find the configuration of the CI?

Manually locally. CI is at https://buildkite.com/nearprotocol/rainbow-bridge/settings, but i'll make it first fully work locally then fix ci.

**Comment by nearmax** [comment]
Found the issue.
