### ISSUE TITLE
CI environment gets poluted by old runs

### ISSUE THREAD

**Issue by chefsale** [near/rainbow-bridge#121]
Example of a run which didn't clean the previous run, as machines can be reused for runs as it looks like. cc: @nearmax @ailisp 

e2e test as an example:
https://buildkite.com/nearprotocol/rainbow-bridge/builds/121#3942c1b6-0c3d-4821-a430-ce0ace4c754c

```

[2020-06-24T20:16:57Z] + node index.js prepare
--
  | [2020-06-24T20:16:58Z] near-core home not specified...
  | [2020-06-24T20:16:58Z]
  | [2020-06-24T20:16:58Z] fatal: destination path '/var/lib/buildkite-agent/.rainbowup/core' already exists and is not an empty directory.
  | [2020-06-24T20:16:58Z]
  | [2020-06-24T20:16:58Z] + node index.js start near-node
  | [2020-06-24T20:16:59Z] child_process.js:669
  | [2020-06-24T20:16:59Z]     throw err;
  | [2020-06-24T20:16:59Z]     ^
  | [2020-06-24T20:16:59Z]
  | [2020-06-24T20:16:59Z] Error: Command failed: ~/.rainbowup/nearup/nearup localnet --num-nodes 1 --binary-path ~/.rainbowup/core/target/debug
  | [2020-06-24T20:16:59Z]     at checkExecSyncError (child_process.js:629:11)
  | [2020-06-24T20:16:59Z]     at execSync (child_process.js:666:13)
  | [2020-06-24T20:16:59Z]     at Request.request [as _callback] (/var/lib/buildkite-agent/builds/buildkite-i-0c8a9ab303f0cd5c5-1/nearprotocol/rainbow-bridge/environment/commands/start/near.js:15:29)
  | [2020-06-24T20:16:59Z]     at self.callback (/var/lib/buildkite-agent/builds/buildkite-i-0c8a9ab303f0cd5c5-1/nearprotocol/rainbow-bridge/environment/node_modules/request/request.js:185:22)
  | [2020-06-24T20:16:59Z]     at Request.emit (events.js:198:13)
  | [2020-06-24T20:16:59Z]     at Request.onRequestError (/var/lib/buildkite-agent/builds/buildkite-i-0c8a9ab303f0cd5c5-1/nearprotocol/rainbow-bridge/environment/node_modules/request/request.js:877:8)
  | [2020-06-24T20:16:59Z]     at ClientRequest.emit (events.js:198:13)
  | [2020-06-24T20:16:59Z]     at Socket.socketErrorListener (_http_client.js:401:9)
  | [2020-06-24T20:16:59Z]     at Socket.emit (events.js:198:13)
  | [2020-06-24T20:16:59Z]     at emitErrorNT (internal/streams/destroy.js:91:8)
  | [2020-06-24T20:16:59Z]     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
```

**Comment by chefsale** [comment]
Fixed the clean method as well, baked a new image with automatic disconnect of the agent:
nearcore-ci-20200624

**Comment by chefsale** [comment]
Even after adding the disconnect it still happens: https://buildkite.com/nearprotocol/rainbow-bridge/builds/135#b13b0963-69e4-4e45-83b0-348f3b9144c5, as most likely they are using a period in between the shutdown to get a job as mentioned previously. We will need to make sure that we do better job of cleaning.
