### ISSUE TITLE
Trouble run eth-relay

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#171]
Today run eth-relay disfunctional, it's log is fully:
```
2|eth-relay  | 2020-07-14 10:56:53.182: TypeError: Cannot read property 'hash' of null
2|eth-relay  | 2020-07-14 10:56:53.182:     at Eth2NearRelay.run (/Users/bo/workspace/rainbow-bridge/environment/lib/eth2near-relay.js:57:55)
2|eth-relay  | 2020-07-14 10:56:53.182:     at runMicrotasks (<anonymous>)
2|eth-relay  | 2020-07-14 10:56:53.182:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2|eth-relay  | 2020-07-14 10:56:53.182:     at async Command.execute (/Users/bo/workspace/rainbow-bridge/environment/commands/start/eth-relay.js:52:13)
2|eth-relay  | 2020-07-14 10:56:53.182:     at async Promise.all (index 0)
2|eth-relay  | 2020-07-14 10:56:53.182:     at async /Users/bo/workspace/rainbow-bridge/environment/index.js:444:16

...
```
Then it begin to backtrace, but that decrease height to negavie
```
...
2|eth-relay  | 2020-07-14 10:57:17.099: Block 0x78aeb53288e1b22c9220e937732d1ea5cc1d1986ec7342cca5c3458622acab10 height: -151 is not known to the client. Backtracking.
```

**Comment by ailisp** [comment]
Not reproducible, probably due to clean command didn't clean ~/.near/localnet/data and it's fixed
