### ISSUE TITLE
near2eth transfer takes forever because DB Not Found Error in near-relay, test with latest nearcore

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#175]
https://buildkite.com/nearprotocol/nearcore/builds/2547#bbbad0f6-6d44-4e66-a7b2-d5203a1ebb78

```
1|near-relay  | 2020-07-14 23:09:07.602:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:08.607: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:08.607:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:08.607:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:09.613: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:09.614:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:09.614:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:10.621: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:10.621:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:10.621:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:11.625: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:11.625:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:11.625:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:12.645: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:12.646:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:12.646:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:15.104: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:15.104:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:15.104:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:16.108: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:16.108:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:16.108:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:17.112: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:17.112:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:17.112:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:18.115: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:18.115:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:18.115:  Backtrace: 
1|near-relay  | 2020-07-14 23:09:19.118: Encountered error while requesting light client block Error: [-32000] Server error: DB Not Found Error: BLOCK HEADER: 8qv5Dxctz4M1XPoj9ySrTQZhvvpYm6juovxFFBAK1vbs 
1|near-relay  | 2020-07-14 23:09:19.118:  Cause: Unknown 
1|near-relay  | 2020-07-14 23:09:19.118:  Backtrace: 
```

**Comment by bowenwang1996** [comment]
which network is this?

**Comment by ailisp** [comment]
Localnet with latest nearcore master

**Comment by bowenwang1996** [comment]
that's weird. is there a way to reproduce?

**Comment by ailisp** [comment]
Rerun above pipeline probably would reproduce (i rerun once and it happened). It will repetitively print 
```

[2020-07-14T23:09:23Z] Block 362 is not available on the light client yet. Current height of light client is 123. Sleeping 10 seconds.
--
And when that happens, gcloud compute ssh bridge-expensive-d36e7553c3da323b4e108d4fe9b4b55e:
find instance name at `ENV` of the job, remove `-1` suffix
```
BUILDKITE_AGENT_NAME="bridge-expensive-d36e7553c3da323b4e108d4fe9b4b55e-1"
```
`sudo su bo`, and see any pm2 logs there (might need npm i -g pm2 first)

To repro locally, checkout nearcore at that commit, and set LOCAL_CORE_SRC, then run e2e.sh

**Comment by bowenwang1996** [comment]
I tried to run it locally but got
```
+ node index.js start near-node
child_process.js:660
    throw err;
    ^

Error: Command failed: python3 ~/.rainbow/nearup/main.py localnet --num-nodes 1 --binary-path ~/.rainbow/core/target/debug
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Request._callback (/Users/bowenwang/NEAR/rainbow-bridge/environment/commands/start/near.js:15:29)
    at self.callback (/Users/bowenwang/NEAR/rainbow-bridge/environment/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.onRequestError (/Users/bowenwang/NEAR/rainbow-bridge/environment/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:203:13)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 54 68 65 72 65 20 69 73 20 61 6c 72 65 61 64 79 20 62 69 6e 61 72 79 20 6e 6f 64 65 73 20 72 75 6e 6e 69 6e 67 2e 20 53 74 6f 70 20 69 74 20 75 73 69 ... 79 more bytes>,
    <Buffer >
  ],
  pid: 93072,
  stdout: <Buffer 54 68 65 72 65 20 69 73 20 61 6c 72 65 61 64 79 20 62 69 6e 61 72 79 20 6e 6f 64 65 73 20 72 75 6e 6e 69 6e 67 2e 20 53 74 6f 70 20 69 74 20 75 73 69 ... 79 more bytes>,
  stderr: <Buffer >
}
```

**Comment by ailisp** [comment]
Are you able to run
```
python3 ~/.rainbow/nearup/main.py localnet --num-nodes 1 --binary-path ~/.rainbow/core/target/debug
```
now?
Possibly old ~/.near/localnet wasn't cleaned due to a bug of index.js clean, which is just merged

**Comment by ailisp** [comment]
We still have this issue in nearcore ci, although we're sure rainbow-bridge works with latest nearcore in rainbow-bridge ci, might be some ci script wrong in nearcore. i'll debug
