### ISSUE TITLE
TypeError: Cannot read property '*' of null.

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#331]
eth2near-relay generates lots of errors of the following pattern: `TypeError: Cannot read property 'difficulty' of null`.
This happens because sometimes JS dependencies return objects that are null or have missing properties. See logs https://drive.google.com/file/d/1ni244HjdSAIh-ZDVWuz5dcmkGxX3De-Y/view?usp=sharing

So far there are two types of such error:
```
2020-08-27 23:55:56.783: Failed to get or parse block 8579110: TypeError: Cannot read property 'difficulty' of null
```
```
2020-08-27 23:56:01.040: TypeError: Cannot read property 'elements' of undefined
2020-08-27 23:56:01.040:     at Eth2NearRelay.submitBlock (/home/max/rainbow-bridge/lib/eth2near-relay.js:138:25)
2020-08-27 23:56:01.040:     at Eth2NearRelay.run (/home/max/rainbow-bridge/lib/eth2near-relay.js:94:38)
2020-08-27 23:56:01.040:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by djsatok** [comment]
Close in favor of https://github.com/near/rainbow-bridge/issues/469
