### ISSUE TITLE
inconsistency between calls to transfer 

### ISSUE THREAD

**Issue by theisen1337** [near/rainbow-bridge#353]
## Issue
Transferring from Either ec20 to Near crashes about 50% of the time.

## reproducing the issue.
Utilizing Rainbow-bridge-cli on Ubuntu 18 AWS Ec2 following directions exactly.
using Rinkeby testnetwork via metamask, and near wallet both on chrome.

## Command that causes the error:
`rainbow transfer-eth-erc20-to-near --amount 100 --eth-sender-sk <key> --near-receiver-account <near account>`

## **Successful call output:**
```
test_thomas.testnet
Transferring 100 tokens from 0x8151a8F90267bFf183E06921841C5dE774499388 ERC20. From 0xf30e8d9D3B4E6C5308A2b9e001347CEBc27669f2 sender to test_thomas.testnet recipient
Near Client contract is currently at block 7233117. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233118. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233119. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233119. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233120. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233120. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233121. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233122. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233122. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Near Client contract is currently at block 7233123. Waiting for block 7233114 to be confirmed. Sleeping for 10 sec.
Balance of test_thomas.testnet before the transfer is 811
TxHash 8AWdicFB43wEfyJAmYjNHSXChBQDUrVUGb7fgPB457TP
[
  'token: 8151a8f90267bff183e06921841c5de774499388; sender: f30e8d9d3b4e6c5308a2b9e001347cebc27669f2; amount: 100; recipient: test_thomas.testnet',
  'Refunding 42800000000000000000000 tokens for storage to test_thomas.testnet'
]
```

## **Error call output:**
```
test_thomas.testnet
Approving token transfer.
Approved token transfer.
Transferring tokens from the ERC20 account to the token locker account.
Success tranfer to locker
(node:20397) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'transactions' of null
    at EthProofExtractor.buildTrie (/home/ubuntu/.nvm/versions/node/v12.18.4/lib/node_modules/rainbow-bridge-cli/node_modules/rainbow-bridge-lib/eth-proof-extractor/index.js:32:13)
    at Function.findProof (/home/ubuntu/.nvm/versions/node/v12.18.4/lib/node_modules/rainbow-bridge-cli/node_modules/rainbow-bridge-lib/transfer-eth-erc20/to-near.js:88:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.execute (/home/ubuntu/.nvm/versions/node/v12.18.4/lib/node_modules/rainbow-bridge-cli/node_modules/rainbow-bridge-lib/transfer-eth-erc20/to-near.js:352:7)    at async Promise.all (index 0)
    at async /home/ubuntu/.nvm/versions/node/v12.18.4/lib/node_modules/rainbow-bridge-cli/index.js:561:5
(node:20397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)
(node:20397) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by djsatok** [comment]
The support of CLI for transfer will be dropped soon. See the #482
Generally transfers would be available from the FE: https://github.com/near/rainbow-bridge-frontend/ or from the step-by-step-guide: https://github.com/djsatok/bridge-testing
