### ISSUE TITLE
Near2Eth fails to submit transaction on Ropsten

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge#472]
Realyer was failing with following error in Ropsten:

```
2021-02-01 14:39:07.774: Error Error: Returned error: replacement transaction underpriced
2021-02-01 14:39:07.774:     at Object.ErrorResponse (/home/ubuntu/rainbow-bridge/node_modules/web3-core-helpers/src/errors.js:29:16)
2021-02-01 14:39:07.774:     at /home/ubuntu/rainbow-bridge/node_modules/web3-core-requestmanager/src/index.js:140:36
2021-02-01 14:39:07.774:     at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/rainbow-bridge/node_modules/web3-providers-http/src/index.js:110:13)
2021-02-01 14:39:07.774:     at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/rainbow-bridge/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2021-02-01 14:39:07.774:     at XMLHttpRequest._setReadyState (/home/ubuntu/rainbow-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2021-02-01 14:39:07.774:     at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/rainbow-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2021-02-01 14:39:07.774:     at IncomingMessage.<anonymous> (/home/ubuntu/rainbow-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2021-02-01 14:39:07.774:     at IncomingMessage.emit (node:events:388:22)
2021-02-01 14:39:07.774:     at endReadableNT (node:internal/streams/readable:1295:12)
2021-02-01 14:39:07.774:     at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

**Comment by mfornet** [comment]
This happens when previous transaction is not included in a block, most likely due to some high increase in gas price on Ropsten. Relayer tries to re-submit same transaction at the same price, but previous transaction is not replaced.

Solution: Manually increase gas price by passing parameter, for example use twice the price with: `--eth-gas-multiplier 2`.
