### ISSUE TITLE
eth2near relayer failing with `GasLimitExceeded`

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge#530]
There is a limit per transaction of 200 Tgas, and currently calling `add_block_header` takes more than that amount in Ropsten. 

```
GasLimitExceeded [Error]: Exceeded the maximum amount of gas allowed to burn per contract
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at Object.parseRpcError (/home/ubuntu/rainbow-bridge/node_modules/near-api-js/lib/utils/rpc_errors.js:38:19)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at Account.signAndSendTransaction (/home/ubuntu/rainbow-bridge/node_modules/near-api-js/lib/account.js:116:36)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at runMicrotasks (<anonymous>)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at processTicksAndRejections (node:internal/process/task_queues:93:5)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at async Eth2NearRelay.run (/home/ubuntu/rainbow-bridge/eth2near/eth2near-block-relay/index.js:151:11)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at async execute (/home/ubuntu/rainbow-bridge/cli/commands/start/eth2near-relay.js:80:7)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at async Command.<anonymous> (/home/ubuntu/rainbow-bridge/utils/config/index.js:38:31)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at async Promise.all (index 0)
21|eth2near-relay  | 2021-03-15 12:01:00.023:     at async /home/ubuntu/rainbow-bridge/cli/index.js:910:3 {
21|eth2near-relay  | 2021-03-15 12:01:00.023:   type: 'GasLimitExceeded',
21|eth2near-relay  | 2021-03-15 12:01:00.023:   index: 0
21|eth2near-relay  | 2021-03-15 12:01:00.023: }
```

**Comment by bowenwang1996** [comment]
> per transaction of 200 Tgas

It is actually 300T. 200T is the per function call limit.
