### ISSUE TITLE
near2eth relayer Fail with transaction was not mined

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge#533]
```
Error Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
0|near2eth-relay  | 2021-03-16 10:32:51.415:     at Object.TransactionError (/home/ubuntu/rainbow-bridge/node_modules/web3-core-helpers/src/errors.js:63:21)
0|near2eth-relay  | 2021-03-16 10:32:51.415:     at /home/ubuntu/rainbow-bridge/node_modules/web3-core-method/src/index.js:485:40
0|near2eth-relay  | 2021-03-16 10:32:51.415:     at runMicrotasks (<anonymous>)
0|near2eth-relay  | 2021-03-16 10:32:51.415:     at processTicksAndRejections (node:internal/process/task_queues:93:5) {
0|near2eth-relay  | 2021-03-16 10:32:51.415:   receipt: undefined
0|near2eth-relay  | 2021-03-16 10:32:51.415: }
```

Transaction was mined [5 minute later](https://etherscan.io/tx/0x55ccaa3c5396ad9cdbe45d033bf22908b87eec47e022eb6a38c4f2d404fd7f6a) though. After this relayer is sleeping for `errorDelay` seconds. 

We need to handle each type of error independently so we are sure relayer will react properly to each situation. Currently `errorDelay` in mainnet is set up to 24 hours, so I'm decreasing to `maxDelay` (12.5 hours)

**Comment by mfornet** [comment]
This is one of the errors that should be handled by #534
