### ISSUE TITLE
Unclear errors on setup of the eth-relay

### ISSUE THREAD

**Issue by chefsale** [near/rainbow-bridge#91]
There are cases where we don't pass all the needed parameters for setup of the services we have and we get ugly stacktraces like this one. It's not really clear why this is happening and catching these exceptions with a nice error message like: Master Account ID missing please do XYZ would be a better user expirience.

cc: @nearmax 

```
eth-relay_1  | (node:1) Warning: N-API is an experimental feature and could change at any time.
eth-relay_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
eth-relay_1  |     at Function.fromString (/usr/src/environment/node_modules/nearlib/lib/utils/key_pair.js:61:34)
eth-relay_1  |     at Command.execute (/usr/src/environment/commands/start/eth-relay.js:53:89)
eth-relay_1  |     at Command.listener [as _actionHandler] (/usr/src/environment/node_modules/commander/index.js:413:31)
eth-relay_1  |     at Command._parseCommand (/usr/src/environment/node_modules/commander/index.js:914:14)
eth-relay_1  |     at Command._dispatchSubcommand (/usr/src/environment/node_modules/commander/index.js:865:18)
eth-relay_1  |     at Command._parseCommand (/usr/src/environment/node_modules/commander/index.js:882:12)
eth-relay_1  |     at Command._dispatchSubcommand (/usr/src/environment/node_modules/commander/index.js:865:18)
eth-relay_1  |     at Command._parseCommand (/usr/src/environment/node_modules/commander/index.js:882:12)
eth-relay_1  |     at Command.parse (/usr/src/environment/node_modules/commander/index.js:717:10)
eth-relay_1  |     at Command.parseAsync (/usr/src/environment/node_modules/commander/index.js:744:10)
eth-relay_1  |     at /usr/src/environment/index.js:204:30
eth-relay_1  |     at Object.<anonymous> (/usr/src/environment/index.js:204:58)
eth-relay_1  |     at Module._compile (module.js:652:30)
eth-relay_1  |     at Object.Module._extensions..js (module.js:663:10)
eth-relay_1  |     at Module.load (module.js:565:32)
eth-relay_1  |     at tryModuleLoad (module.js:505:12)
eth-relay_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
eth-relay_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nearmax** [comment]
Is it because you have manually edited config.js and replaced some secret keys with empty strings?

**Comment by chefsale** [comment]
Nope, I get this when I forgot to pass the right ones, aka some of them are missing. It would be nice to know which parameters I haven't provided.

**Comment by nearmax** [comment]
I agree.

**Comment by nearmax** [comment]
This seems to be gone.
